#cloud-config

packages:
  - podman
  - podman-compose

snap:
  commands:
    0: [install, core]
    1: [refresh, core]
    2: [install, --classic, certbot]

write_files:
  #
  # This should NOT be updated unless you are intending to redeploy the bootstrap server
  #
  - content: |
      services:
        bootstrap-iroh-relay:
          image: ghcr.io/holochain/kitsune2_bootstrap_srv_iroh_relay@sha256:79a7109d2224a184c00333a31bb91a410044d356adc6446beb11b9beac5af13e
          command:
            - kitsune2-bootstrap-srv
            - --production
            - --listen
            - "[::]:443"
            - --tls-cert
            - /etc/letsencrypt/live/dev-test-bootstrap2-iroh-relay.holochain.org/fullchain.pem
            - --tls-key
            - /etc/letsencrypt/live/dev-test-bootstrap2-iroh-relay.holochain.org/privkey.pem
          environment:
            - RUST_LOG=info
          network_mode: host
          volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/
          restart: unless-stopped
    path: /opt/bootstrap_srv/docker-compose.yaml
    permissions: "0644"
