#cloud-config

packages:
  - podman
  - podman-compose

snap:
  commands:
    0: [install, core]
    1: [refresh, core]
    2: [install, --classic, certbot]

write_files:
  #
  # This should NOT be updated unless you are intending to redeploy the bootstrap server
  #
  - content: |
      services:
        bootstrap:
          image: ghcr.io/holochain/kitsune2_bootstrap_srv@sha256:fbea9a7a44e574059edd7cca38689be8764bb85c7217e7ee57b3ca9628f74d4c
          command:
            - kitsune2-bootstrap-srv
            - --production
            - --listen
            - "[::]:443"
            - --tls-cert
            - /etc/letsencrypt/live/dev-test-bootstrap2.holochain.org/fullchain.pem
            - --tls-key
            - /etc/letsencrypt/live/dev-test-bootstrap2.holochain.org/privkey.pem
          environment:
            - RUST_LOG=info
          network_mode: host
          volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/
          restart: unless-stopped
    path: /opt/bootstrap_srv/docker-compose.yaml
    permissions: "0644"
