services:
  bootstrap:
    image: ghcr.io/holochain/kitsune2_bootstrap_srv:v0.2.5
    command:
      - kitsune2-bootstrap-srv
      - --production
      - --listen
      - "[::]:443"
      - --tls-cert
      - /etc/letsencrypt/live/dev-test-bootstrap2-auth.holochain.org/fullchain.pem
      - --tls-key
      - /etc/letsencrypt/live/dev-test-bootstrap2-auth.holochain.org/privkey.pem
      - --authentication-hook-server
      - http://auth:80/authenticate
    environment:
      - RUST_LOG=info
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    restart: unless-stopped
  auth:
    image: ghcr.io/holochain/kitsune2_test_auth_hook_server:v0.2.5
    command:
      - test-auth-hook-server
      - "[::]:80"
    environment:
      - RUST_LOG=info
    ports:
      - "80:80"
    restart: unless-stopped
